### ISSUE TITLE
MQTT Password

### ISSUE THREAD

**Issue by jjanderson** [tinaught/appkettleapi#8]
Hi, Thanks for all your work on this,

Can you let me know if there are any args for username and password?

I cannot seem to run the script with username and password.

Many thanks

**Comment by tinaught** [comment]
Hi there, thanks for looking at this! I don't have the kettle anymore so I cannot test/develop this further, but it should be easy to add mqtt authentication - see docs here: https://pypi.org/project/paho-mqtt/. If you manage to implement it and do a PR I'll merge it here for others to enjoy

**Comment by jjanderson** [comment]
Hi, thanks for getting back to me. unfortunately I wouldn't know where to start, but I will give it a go.

**Comment by jjanderson** [comment]
ok, I think I actually got somewhere.

in mosquitto I am now getting

```
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/temperature', ... (2 bytes))
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/target_temp', ... (3 bytes))
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/set_target_temp', ... (3 bytes))
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/status', ... (7 bytes))
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/power', ... (3 bytes))
2023-03-17 20:09:32: Received PUBLISH from auto-C2708C14-7F02-EB62-D868-A6ECCFB65654 (d0, q0, r0, m0, 'stat/appKettle/version', ... (5 bytes))
```
and this in the terminal after close

```
Traceback (most recent call last):
  File "/home/jjanderson/appkettleapi-master/appkettle_mqtt.py", line 581, in <module>
    argparser()
  File "/home/jjanderson/appkettleapi-master/appkettle_mqtt.py", line 577, in argparser
    main_loop((args.host, args.port), args.imei, args.mqtt, args.auth)
  File "/home/jjanderson/appkettleapi-master/appkettle_mqtt.py", line 551, in main_loop
    time.sleep(0.2)  # build-in a little sleep
  File "/home/jjanderson/appkettleapi-master/appkettle_mqtt.py", line 471, in cb_signal_handler
    user_input = input("prompt|>> ")
  File "/home/jjanderson/appkettleapi-master/appkettle_mqtt.py", line 471, in cb_signal_handler
    user_input = input("prompt|>> ")
RuntimeError: can't re-enter readline
root@ubuntu-desktop-dev:/home/jjanderson/appkettleapi-master#
```

I have forked and running here: https://github.com/jjanderson/appkettleapi/edit/master/appkettle_mqtt.py

**Comment by jjanderson** [comment]
Hi,

I have now connected successfully and retrieving kettle data.

I am however having some issues with the switches. Could you possibly remember what the command topics were?

Another thing, is that in the broker, my topics come up as **stat**/appKettle/temperature I am not sure where that leading stat is coming from, this could possible be where my issues lie in sending the command on topic?

Any help much appreciated.

**Comment by jjanderson** [comment]
ended up using the addon as per this post https://community.home-assistant.io/t/boil-my-smart-kettle-from-ha/21805/57
